/* PICTURE DESKTOP */
export const CHANGE_PICTURE_DESKTOP = "CHANGE_PICTURE_DESKTOP"
export const CHANGE_PICTURE_POSITION_DESKTOP = "CHANGE_PICTURE_POSITION_DESKTOP"

/* PICTURE MOBILE */
export const CHANGE_PICTURE_MOBILE = "CHANGE_PICTURE_MOBILE"
export const CHANGE_PICTURE_POSITION_MOBILE = "CHANGE_PICTURE_POSITION_MOBILE"


